# Generated by Django 6.0.4 on 2026-05-26 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='cv',
            field=models.FileField(default='', upload_to='cvs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
