# Generated by Django 5.0.6 on 2026-06-19 07:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jobseeker_created_at_jobseeker_cv_jobseeker_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cv'),
        ),
    ]
